# Generated by Django 5.2 on 2025-05-10 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('CIN', models.CharField(blank=True, max_length=20, null=True)),
                ('shiftPeriod', models.CharField(choices=[('morning', 'Matin (6h - 14h)'), ('afternoon', 'Après-midi (14h - 22h)'), ('night', 'Nuit (22h - 6h)')], max_length=20)),
                ('supervisor', models.CharField(max_length=100)),
                ('equipment', models.JSONField(default=list)),
                ('address', models.TextField(blank=True, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('joinDate', models.DateField()),
            ],
            options={
                'verbose_name': 'Chauffeur',
                'verbose_name_plural': 'Chauffeurs',
                'db_table': 'authentification_driver',
            },
        ),
        migrations.CreateModel(
            name='Engin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('type_engin', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('annee_fabrication', models.IntegerField()),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('occupe', 'Occupé'), ('maintenance', 'En maintenance'), ('hors_service', 'Hors service'), ('reserve', 'Réservé')], max_length=20)),
                ('maintenance_info', models.TextField(blank=True, null=True)),
                ('date_acquisition', models.DateField()),
                ('kilometrage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prochaine_maintenance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Navire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('imo', models.CharField(max_length=7, unique=True)),
                ('type_operation', models.CharField(choices=[('import', 'Import'), ('export', 'Export'), ('transit', 'Transit')], max_length=10)),
                ('port_origine', models.CharField(max_length=100)),
                ('poste', models.CharField(choices=[('1', 'Poste 1'), ('2', 'Poste 2'), ('3', 'Poste 3'), ('4', 'Poste 4')], max_length=10)),
                ('heure_arrivee', models.DateTimeField()),
                ('duree_sejour', models.IntegerField(help_text='Durée en heures')),
                ('heure_depart', models.DateTimeField(blank=True, null=True)),
                ('type_marchandise', models.CharField(choices=[('containers', 'Conteneurs'), ('bulk', 'Vrac'), ('general', 'Marchandises Générales'), ('vehicles', 'Véhicules')], max_length=20)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Accosté', 'Accosté'), ('En opération', 'En opération'), ('Terminé', 'Terminé')], default='En attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('chef_escale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Navire',
                'verbose_name_plural': 'Navires',
                'ordering': ['-heure_arrivee'],
            },
        ),
    ]
