# Generated by Django 5.2 on 2025-05-10 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='engin',
            table='engin',
        ),
    ]
