# Generated by Django 5.2 on 2025-05-11 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_alter_engin_options_alter_driver_supervisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='equipment',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='driver',
            name='firstname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='joinDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='shiftPeriod',
            field=models.CharField(blank=True, choices=[('morning', 'Matin (6h - 14h)'), ('afternoon', 'Après-midi (14h - 22h)'), ('night', 'Nuit (22h - 6h)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='supervisor',
            field=models.ForeignKey(blank=True, db_column='supervisor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='authentification.driver'),
        ),
    ]
